version: "3"
services:
  py:
    image: aaweaver9/py:latest
    container_name: py
    volumes:
      - ..:/app
    working_dir: /app
    networks:
      - mongo-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../data/mongo:/data/db
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express:1-20-alpine3.19
    container_name: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongo-net
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo

networks:
  mongo-net:
    driver: bridge